### PR TITLE
Some more product brief

### PR DESCRIPTION
**Pull request by lightelf76**

### CODE REVIEW

**Comment by fifteenhex** [comment]
Awesome. Seems there are lot more chips than I thought.

**Comment by lightelf76** [comment]
It seems like SigmaStar transitioning to more open business model, at least for chinese-speaking peoples. There is a SigmaStarDocs site http://comake.online/, linked from main SigmaStar page,but access to download area need registration with chinese phone number. 24.12.2020, 15:03, "Daniel Palmer" <notifications@github.com>: Awesome. Seems there are lot more chips than I thought.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fifteenhex** [comment]
I had seen the page before but I hadn't realised they had uploaded anything.
Will be interesting to see if they ever upload some documents with register descriptions.

**Comment by lightelf76** [comment]
Hope some info will leak later. I am specially interested in HW documents - like electrical characteristics, appnotes, etc - to design board. 24.12.2020, 15:20, "Daniel Palmer" <notifications@github.com>: I had seen the page before but I hadn't realised they had uploaded anything.Will be interesting to see if they ever upload some documents with register descriptions.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fifteenhex** [comment]
That would be nice. When I made my board (https://github.com/breadbee/breadbee) I had to make a lot of guesses.
Are you able to get hold of their chips? When I was trying to get the MSC313E originally it was very difficult.

**Comment by lightelf76** [comment]
Samples can be ordered from Aliexpress (I did, waiting for package).https://aliexpress.ru/item/1005001806069995.html 24.12.2020, 15:37, "Daniel Palmer" <notifications@github.com>: That would be nice. When I made my board (https://github.com/breadbee/breadbee) I had to make a lot of guesses.Are you able to get hold of their chips? When I was trying to get the MSC313E originally it was very difficult.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fifteenhex** [comment]
Ah, yeah I bought some of those from taobao. They are bit cheaper there.
The SSC325 (The IP camera chip) seems to also be available now but the versions with more memory, AI etc are hard to get.

**Comment by lightelf76** [comment]
Hello! Another chip datasheet  24.12.2020, 15:03, "Daniel Palmer" <notifications@github.com>: Awesome. Seems there are lot more chips than I thought.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fifteenhex** [comment]
Not seeing anything.. I'm not sure if email attachments come through to github issues.

**Comment by lightelf76** [comment]
Hello Daniel!Just found some info for SSD210, hope these images not so blurried.

**Pull request merged**
