### PR TITLE
Pinount info for SSD201

### PR DESCRIPTION
**Pull request by lightelf76**

### CODE REVIEW

**Comment by fifteenhex** [comment]
Hi,

Thanks for the PR. I think this adds a file that comes from the internal SDK? I'm not sure we should do that..
Datasheets that have already leaked to the internet I think are ok to reproduce because of "educational fair use" but parts of the vendor SDK aside from the GPL parts like the kernel and u-boot source are a bit risky.

**Comment by lightelf76** [comment]
This file come from IDO-SOM2D01 SDK, which is available from [Industio](http://doc.industio.com/docs/ssd20x-system/page_0)

**Comment by fifteenhex** [comment]
Hi,

Interesting. I hadn't realised they had realised the SDK like that. Could we link to that instead? I think linking to the SDK someone else has released is ok (their problem if they didn't have permission) but uploading proprietary bits from the SDK is not so good.

It'd be nice if we could have the table in a markdown format too as Excel files are a pain.

Thanks.

**Comment by lightelf76** [comment]
The the SDK "release" just links to Baidu cloud, which is a pain to get from.

**Comment by fifteenhex** [comment]
Yeah. It took me about a week to download the SDK from baidu.
I will rewrite the information in the xls as markdown later today.
Sorry for being strict on this I just don't want to have this repo shut down because of parts of the SDK ending up in it.

**Comment by lightelf76** [comment]
WIDORA did samll board, based on SSD202. There is a interesting page on Widora site: https://widora.io/ssd202/index.html 23.12.2020, 10:43, "Daniel Palmer" <notifications@github.com>: Yeah. It took me about a week to download the SDK from baidu.I will rewrite the information in the xls as markdown later today.Sorry for being strict on this I just don't want to have this repo shut down because of parts of the SDK ending up in it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fifteenhex** [comment]
Yeah. I have contacted them already about adding support for their board to mainline linux.
A small amount of support for the ssd202 will be going into linux 5.11.

**Comment by lightelf76** [comment]
Just found interesting forum (chinese), seems like it SigmaStar-related: http://dev.comake.online/ 23.12.2020, 16:07, "Daniel Palmer" <notifications@github.com>: Yeah. I have contacted them already about adding support for their board to mainline linux.A small amount of support for the ssd202 will be going into linux 5.11.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lightelf76** [comment]
Excuse me for bothering you, just a note:there is one more chip in infinity2m family, SSD203D. Which seems like SSD202D with HDMI instead of MIPI DSI.One of devices, based on SSD203D is https://www.joom.com/en/products/5f9bd9de6ab0f001066674fdPlease see feature set comparision for SSD20X family (screenshot) within attachment. 23.12.2020, 16:07, "Daniel Palmer" <notifications@github.com>: Yeah. I have contacted them already about adding support for their board to mainline linux.A small amount of support for the ssd202 will be going into linux 5.11.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fifteenhex** [comment]
No problem at all. I think I had seen mention of the SSD203D somewhere.
I'll get one of these. I think it'll run with the same code all of the other chips work with.

**Pull request closed without merging**
